name: notify shutting down of server

on:
  repository_dispatch:
    types: [notify-shutdown]

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@master
      
      - name: send telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ vars.BEGIN_DESTROY_MESSAGE }}